CREATE PROCEDURE SP_INSERIR_RESULTADO_ANALISE
    @RESULTADO BIT,
    @LINK NVARCHAR(4000),
    @FONTE NVARCHAR(4000) = '',
    @TITULO NVARCHAR(4000) = ''
AS
BEGIN

    DECLARE @ID_NOTICIA INT = (
        SELECT
            ID
        FROM NOTICIA (NOLOCK)
        WHERE LINK = @LINK
    )

    DECLARE @ID_RESULTADO INT = (
        SELECT
            ID
        FROM [RESULTADO-ANALISE] (NOLOCK)
        WHERE NOTICIAS_ID = @ID_NOTICIA
    )

    IF @ID_NOTICIA IS NOT NULL AND @ID_RESULTADO IS NULL
    BEGIN
        INSERT INTO [RESULTADO-ANALISE] (RESULTADO, FONTE, TITULO, NOTICIAS_ID) VALUES
            (@RESULTADO, @FONTE, @TITULO, @ID_NOTICIA)
    END

END